Update to Monaco editor version 0.34.0 and adapt to new API
Link the new version and adapt our setup to match the changed API:

+ Fix error 'Cannot read properties of undefined (reading 'editor.foreground')' described at https://github.com/microsoft/monaco-editor/pull/2764 and https://github.com/atularen/ngx-monaco-editor/issues/259 : Apply the patch from https://github.com/microsoft/monaco-editor/commit/88fd0a6e7f5669e97cea03fd858c8bde7fcfd64b
+ Fix error 'Uncaught Error: a.onDidChangeValue is not a function': Apply the patch https://stackoverflow.com/questions/54795603/always-show-the-show-more-section-in-monaco-editor/73287722#73287722