Support Configuration Of Environment For Running Tests
Adapt to failure seen on AppVeyor:
----
Starting test execution, please wait...
Failed   Get_echo_from_elm_app
Error Message:
 Test method PersistentAppFromElmCode.Test.TestContainer.Get_echo_from_elm_app threw exception:
System.NotImplementedException: Output file not found.
Maybe standard output from compilations helps to find the cause:
Stack Trace:
    at PersistentAppFromElmCode.Common.PersistentAppFromElm019Code.CompileElmToJavascript(IReadOnlyCollection`1 elmCodeFiles, String pathToFileWithElmEntryPoint) in C:\projects\kalmit\implementation\PersistentAppFromElmCode\PersistentAppFromElmCode.Common\PersistentAppFromElmCode.cs:line 134