Work around errors in CSharpCompilation with different syntax tree constructor
Switch to a different implementation to construct the `CSharpSyntaxTree` instance to eliminate some inexplicable errors in the `CSharpCompilation`. In the previous version, the `Emit` on compilation returned errors like the following:
```
(3,7): error CS0246: The type or namespace name 'System.Collections.Generic' could not be found (are you missing a using directive or an assembly reference?)
(10,29): error CS0759: No defining declaration found for implementing declaration of partial method 'PineVMConfiguration.LinkGeneratedOptimizations()'
(19,19): error CS0246: The type or namespace name 'IReadOnlyDictionary<,>' could not be found (are you missing a using directive or an assembly reference?)
(12,13): error CS0103: The name 'DecodeExpressionOverrides' does not exist in the current context
(302,126): error CS0103: The name 'ImmutableArray' does not exist in the current context
(304,129): error CS0103: The name 'ImmutableArray' does not exist in the current context
(308,87): error CS0103: The name 'ImmutableArray' does not exist in the current context
(311,82): error CS0103: The name 'ImmutableArray' does not exist in the current context
(314,95): error CS0103: The name 'ImmutableArray' does not exist in the current context
(318,111): error CS0103: The name 'ImmutableArray' does not exist in the current context
(322,81): error CS0103: The name 'ImmutableArray' does not exist in the current context
(323,79): error CS0103: The name 'ImmutableArray' does not exist in the current context
(326,103): error CS0103: The name 'ImmutableArray' does not exist in the current context
(330,119): error CS0103: The name 'ImmutableArray' does not exist in the current context
(334,95): error CS0103: The name 'ImmutableArray' does not exist in the current context
(338,111): error CS0103: The name 'ImmutableArray' does not exist in the current context
(20,9): error CS0103: The name 'ImmutableDictionary' does not exist in the current context
```