Don't attempt to use HTTPS URL if we don't have cert
Because ASP.NET core crashed with errors like the following, when given also a HTTPS URL:
-----
info: ElmTime.Platform.WebService.PublicAppState[0]
      I did not find 'letsEncryptOptions' in the configuration. I continue without Let's Encrypt.
warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
      Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*;https://*'.
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
      For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN2ABFI40310", Request id "0HN2ABFI40310:00000002": An unhandled exception was thrown by the application.
      System.AggregateException: One or more errors occurred. (Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
      For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.)
       ---> System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
      For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
         at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.Threading.Tasks.Task.Wait()
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass34_0.<Configure>b__5(RestoreFromCompositionEventSequenceResult restoreProcessOk) in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 289
         at Pine.Result`2.Unpack[T](Func`2 fromErr, Func`2 fromOk) in /app/Pine/Result.cs:line 102
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass34_0.<Configure>g__startPublicApp|1() in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 166
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass35_0.<AdminInterfaceRun>g__attemptContinueWithCompositionEvent|15(CompositionEvent compositionLogEvent) in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 971
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass35_1.<<AdminInterfaceRun>g__attemptContinueWithCompositionEventAndSendHttpResponse|17>d.MoveNext() in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 1005
      --- End of stack trace from previous location ---
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass35_1.<<AdminInterfaceRun>g__deployElmApp|1>d.MoveNext() in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 443
      --- End of stack trace from previous location ---
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass35_1.<<AdminInterfaceRun>b__9>d.MoveNext() in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 619
      --- End of stack trace from previous location ---
         at ElmTime.Platform.WebService.StartupAdminInterface.<>c__DisplayClass35_0.<<AdminInterfaceRun>b__0>d.MoveNext() in /app/elm-time/Platform/WebService/StartupAdminInterface.cs:line 751
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:4000/api/deploy-and-migrate-app-state - 500 0 - 39123.0066ms